repos:
  - repo: local
    hooks:
      - id: gofumpt
        name: gofumpt
        description: Run gofumpt
        entry: gofumpt -w
        types: [go]
        language: golang
        pass_filenames: True
      - id: go-mod-tidy
        name: Run go mod tidy
        entry: ./git-hooks/go-mod-tidy
        files: '\.go$|go.mod$|go.sum$'
        language: script
        args: ["."]
        pass_filenames: false