version: '2'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - '6500:5432'
    restart: always
    env_file:
      - ./app.env
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: